[package]
name = "perps-config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { workspace = true }
dotenvy = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = "3"
